### ISSUE TITLE
"Server Error": reason unknown

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#100]
Since I'm not sure what went wrong, here's the screen shots:

![screen shot 2015-08-16 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/13664993/9295633/d440b226-4441-11e5-822c-b294808eed15.png)
![screen shot 2015-08-16 at 6 07 19 pm](https://cloud.githubusercontent.com/assets/13664993/9295634/d6e87e8c-4441-11e5-889f-99e4901519be.png)

**Comment by lexpar** [comment]
Thanks for including a screenshot - I'll try recreating this.

**Comment by lexpar** [comment]
The backed expected there to be two dates - even though the fronted requires only one.

Fixed in 2082e6c864ea0fdc374f0b5847e2ad64a5a3bd41
