### ISSUE TITLE
File Upload / Comments Field

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#103]
The comments field (i.e. free form additional information field) should be able to take html markup, or at least a link markdown feature - I added a link, and [http://www.bach-digital.de/receive/BachDigitalWork_work_00000504](http://www.bach-digital.de/receive/BachDigitalWork_work_00000504 "BWV 434") showed up as raw html text.

**Comment by lexpar** [comment]
Comments for everything now have fancy editors and support Markdown. Fixed in d99b26bdad52c23c294baba6d0c5197cf6d9d8ca

**Comment by musicus** [comment]
Sweet.
