### ISSUE TITLE
Server Error for Bach Brandenburg Concerto persists

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#105]
I'm still getting a "Server Error" for the Bach Brandenburg Concerto. I wanted to upload just one movement and then add the others via the "Update" function. It didn't work. So then I added all three files and it still didn't work. I tried the composition dates as just the end date (as the tooltip recommends) and with the same date as the start and end date, and it failed in both cases. I'm not sure what went wrong. Here's a screenshot:
![screen shot 2015-08-17 at 2 43 13 pm](https://cloud.githubusercontent.com/assets/13664993/9313060/b705efb6-44ee-11e5-8850-f615c9091326.png)
![screen shot 2015-08-17 at 2 43 30 pm](https://cloud.githubusercontent.com/assets/13664993/9313062/b938c600-44ee-11e5-87a3-f134b49e1055.png)

**Comment by lexpar** [comment]
As in #107, I've been updating backend stuff and *should* have blocked off the frontend while I was updating things. I'll keep this issue open in case there really is an error - but I don't think there is.

**Comment by NinaPenner** [comment]
That's alright. Thanks for letting me know. I'll try again later.

**Comment by lexpar** [comment]
Sorry about that - I'm guessing it was frustrating.

**Comment by lexpar** [comment]
I had to delete about a dozen duplicates that were created by you hitting 'submit' and then an error occurring after the piece was saved, but before all its information was filled in. 

You should be able to edit your piece now. Please let me know that it works.
