### ISSUE TITLE
request edit to File Source tooltip

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#106]
It doesn't make sense to me to have the information "This file will be renamed automatically, so does not require a title." as the tool tip for the File Source. It would be better to have this information under the general instructions under "Files". Also, since all files on one's computer have titles, what you're really telling the user is that what that title of the file is doesn't matter. You could just say "The files you upload will be renamed automatically." and I'm sure the rest would be understood. Perhaps this could go right after the sentence about the acceptable file formats? (Speaking of which, I didn't realize that we are interested in people uploading PDFs. I thought that we wanted only XML, MEI, and related formats.)

**Comment by lexpar** [comment]
Maybe we can discuss formats at the next meeting - I haven't really gotten a definitive word from anyone, and I developed on the side of 'if its a likely format to have music in, let it be uploaded'.
