### ISSUE TITLE
Put hyperlinks in comments?

### ISSUE THREAD

**Issue by sagransj** [ELVIS-Project/elvis-database#109]
Would it be possible for URLs listed in the comments for a piece to automatically be converted to hyperlinks? Right now it is possible to add a hyperlink but you have to do it manually. Having hyperlinks can be useful for indicating the source of your files--people can click on them and be taken to the source right away. I put URLs in the comments for many of the pieces I previously uploaded and it would be a hassle to go back through them all and add the links manually. See, for example, this piece: http://database.elvisproject.ca/piece/2436/ (which raises another issue--I put a hyperlink in the comments  to another entry in the old database, which is useless now I suppose, unless there is some way we can get URLs for old database entries to forward to the corresponding entries in the new database).

**Comment by lexpar** [comment]
This is a very low priority issue. I'll keep it open because it could very well be something that could be solved in a few minutes, but it might also take a couple hours.

**Comment by sagransj** [comment]
Okay, sounds good. Thanks!

**Comment by ahankinson** [comment]
The fields support Markdown don't they?

**Comment by lexpar** [comment]
Yup - but this is a new thing, and the old plaintext comments are not hyperlinking the plaintext urls.

**Comment by lexpar** [comment]
Won't do this.
