### ISSUE TITLE
Information & Help

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#113]
I think the Information & Help section is currently more confusing than not: http://database.elvisproject.ca/search/

Maybe keep the AND OR NOT bit, but I don't think the explanation of the green button helps. 

"Clicking on [green plus sign] adds all the files associated with that entry to your downloads" or something like that might be simpler?

**Comment by lexpar** [comment]
The green buttons don't even need to be explained I think. They have mouseover text. I wrote some boolean-phrase examples in their place. Let me know what you think.

**Comment by emilyhopkins** [comment]
Yes! This is way better.
