### ISSUE TITLE
New Composer no longer prompts for Birth/Death dates

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#118]
@slhowes noticed this one and it's not working for me either (I cleared my cache!)

When entering a new composer, the database used to prompt the user for birth and death dates. I tried Francis Poulenc and Karlheinz Stockhausen and it doesn't seem to recognize them as new additions. I tried to make an actual piece with Stockhausen to see if it that would cause it to prompt me then but it let me make a piece without even adding any files. (being able to make a piece without files may be a separate problem!) 

It saves the dates like this:
![screen shot 2015-09-01 at 3 39 50 pm](https://cloud.githubusercontent.com/assets/13374693/9614422/c08b8938-50bf-11e5-8c2a-d4ecc78d1b37.png)

Can you look into this? Thanks!

(Also I deleted the piece but it has kept this entry for the composer -- is there some way to kill it? It's backwards (as per the tooltip issue already submitted in #117) and has no dates...)

**Comment by lexpar** [comment]
Hey Emily - 

Problem should be fixed in a4c7a5657b1880aa0be979ca5fbb66df228bd6bd.

You want me to remove 'Karlheinz, Stockhausen' from the DB, correct?

**Comment by emilyhopkins** [comment]
Yes, please remove him. I don't think the database will be wanting any Stockhausen at all, but either way his name is wrong in that one.

**Comment by emilyhopkins** [comment]
Also, the prompting for dates is working again for me, thanks!

**Comment by lexpar** [comment]
Great - all done. :)
