### ISSUE TITLE
Cleanup Script

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/elvis-database#12]
Eventually we should have a script that checks the database's integrity. It could do things like:

- find files that don't have a database entry
- find database entries that point to missing files

We could run it as a monthly cron job.

**Comment by lexpar** [comment]
This has been fixed for a while.

All zip files, upon finishing being zipped, call a second celery job with a 10 minute delay to prompt their deletion. All movements and pieces delete through to their attachments when they are deleted.
