### ISSUE TITLE
Discrepancy between cart contents and files associated with download cart

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#121]
This was my cart:

![screen shot 2015-09-16 at 5 19 43 pm](https://cloud.githubusercontent.com/assets/13374693/9918862/6864207e-5c97-11e5-8d26-58f211623dea.png)
But then when I click "Select Files to Download" it shows:
![screen shot 2015-09-16 at 5 19 53 pm](https://cloud.githubusercontent.com/assets/13374693/9918878/7791077e-5c97-11e5-809a-2514d49e2ad6.png)

I used to have those quartets in there, but deleted them before downloading the Telemann. The pdfs seem to want to stay, though (the "Piece files")

Any idea what's going on? Problem persists after logging out and in again, and after clearing my cache.

**Comment by emilyhopkins** [comment]
Just noticed that if I click "Remove from Downloads" here, they go away for real:

![screen shot 2015-09-16 at 5 30 42 pm](https://cloud.githubusercontent.com/assets/13374693/9919112/cf88ff6c-5c98-11e5-880c-eafdd1a2932f.png)

The number reflected in my download cart was at "1" before and after removing them though. (It changed earlier when I deleted them from the cart interface)

Looks like the different ways to remove stuff from your cart aren't all talking to each other properly?

**Comment by lexpar** [comment]
This will be fixed in the next update.

**Comment by emilyhopkins** [comment]
Likewise hooray!
