### ISSUE TITLE
Title for downloading movements

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#122]
It would be really helpful if the title for downloading a movement by itself still including the name of the piece it comes from. 

Just seeing "Dolce" like below is potentially ambiguous; would be better to have "Dolce from Sonata for Two Recorders" or similar. (I know it's in "Type" as a tag, but it isn't really the type...)

![screen shot 2015-09-16 at 5 19 43 pm](https://cloud.githubusercontent.com/assets/13374693/9918968/f9a8e0f6-5c97-11e5-931e-d25f7622c1bc.png)

**Comment by emilyhopkins** [comment]
Just wanted to follow this up -- I downloaded a whole bunch of movements to try to do a Rodan workflow and the current naming scheme is pretty hard to work with:

![screen shot 2015-11-02 at 2 11 07 pm](https://cloud.githubusercontent.com/assets/13374693/10891408/d8eadd3a-816b-11e5-96ea-47fd64b67de4.png)

From the file names, all I know is the movement and composer. It would be really useful to also keep Piece name and Movement number, particularly as there are often multiple movements with the same name ("Allegro") for a given composer.

**Comment by lexpar** [comment]
Hierarchical directory-based zip files are coming in the next update!

**Comment by emilyhopkins** [comment]
Hooray! That will be great.

**Comment by AFFogarty** [comment]
Ok, I'm going to close this and mark as duplicate.

**Comment by lexpar** [comment]
Oh yeah it's done.
