### ISSUE TITLE
Search returns duplicate entries

### ISSUE THREAD

**Issue by slhowes** [ELVIS-Project/elvis-database#125]
![duplicates](https://cloud.githubusercontent.com/assets/14061624/10065421/ad374f0c-6253-11e5-8689-f50469e67a4c.gif)
But entries with the same title link to the same piece, so they aren't actually duplicate entries, just duplicate results... In this screenshot I searched 'Frescobaldi.'

**Comment by slhowes** [comment]
Update: this only happens when I search for pieces that I've uploaded. When I search 'Bach' everything is fine. I haven't uploaded any Bach, but I've uploaded lots of Frescobaldi.

**Comment by lexpar** [comment]
Odd - especially since I've just checked, and you're not actually creating duplicates. I wonder what's going on here...

**Comment by lexpar** [comment]
Probably the piece is getting indexed twice without deleting the first document. I wonder when that happens.

**Comment by slhowes** [comment]
Could it be that I'm seeing it twice because I'm also a super user? Once for normal usership and once for super usership? I don't know if that makes sense, but now that I think about it, I don't think this ever happened before I was a superuser.

**Comment by lexpar** [comment]
Good thinking, but I don't think that's it. Your user status isn't being check on the search - the results are coming from a search server that doesn't care who's asking for results. It must be for some reason the item exists twice in the search server's records. Might be hard to track down!

**Comment by ahankinson** [comment]
https://github.com/ELVIS-Project/elvis-database/blob/master/elvis/models/piece.py#L167

Why not:

`record = solrconn.query("item_id:{0} AND type:elvis_piece".format(instance.item_id)`

?

**Comment by lexpar** [comment]
Aha!

**Comment by lexpar** [comment]
Or -not. The item_id in the solr document is in fact the instance.id, as you can see on line 135 of the same piece of code. So, that solr_delete thing actually is working properly.

**Comment by ahankinson** [comment]
Why are you casting it to an `int` when you index it?

https://github.com/ELVIS-Project/elvis-database/blob/master/elvis/models/piece.py#L135

**Comment by lexpar** [comment]
Dunno - it should already be an int.

**Comment by lexpar** [comment]
Sam - have you updated that piece after creating it? It might be a problem with the backend there...

**Comment by lexpar** [comment]
There is something extremely fishy going on here.

The newest piece in the database shows no duplicates on searches:
http://database.elvisproject.ca/search/?q=Brandenburg%20Concerto%20no.%205,%20BWV%201050&tags=D%20Major&type=elvis_piece&number_of_voices=0&composer_name=Bach,%20Johann%20Sebastian&page=1

That piece being the first in the search, Brandenburg Concerto no. 5, BWV 1050.

Meanwhile, the *second* oldest piece in the database, which you uploaded Sam, has a frankly *whacky* number of duplicates, especially that first movement.

http://database.elvisproject.ca/search/?q=Sonata%20in%20G%20minor,%20Op.%204%20No.%202

Maybe it does have something to do with how uploads are handled for superusers? Or something to do with the update form?

**Comment by lexpar** [comment]
Aha (for real this time).

I've confirmed that this only occurs after *updating* the piece - and has nothing to do with uploading. I'll have a closer look.

**Comment by lexpar** [comment]
Far weirder aha - it doesn't happen locally. Maybe a problem with the solr installation on the production server?

**Comment by lexpar** [comment]
Welp - its a weird one. Multiple records are being created even though every time a piece saves itself, it should check for old records and delete them. I will try to implement a fix so that it actually deletes ALL records with the same id/type (instead of assuming there is at most 1) - but this is definitely a band-aid to some deeper issue.

In any case, I appreciate the update on the issue Sam. The search system for the DB needs serious attention. Twice this summer I 'overhauled' it - but I never ripped it down and rebuilt it from a better foundation. The pressure of me jamming a bunch of new functionality on top of an old system built by people I've never talked to has become overwhelming. I very much would like to wipe the whole thing and start fresh.

Hopefully I can do so in a couple weeks. It's top of my list after getting a different project up to a decent place. At least no permanent damage is being done - the piece is being faithfully represented in the database, there's just huge confusion over getting that information to and from the search server.

**Comment by slhowes** [comment]
Yes! I have definitely updated lots of the Frescobaldi pieces that I've uploaded. Same with that G minor Corelli piece. All those duplicates for the first movement must be from when I tried to update over and over when the description text wasn't updating (looks like I tried about 5 times before finally submitting an issue haha).

**Comment by slhowes** [comment]
I'm glad that my obsessive nature helped us find this problem.

**Comment by lexpar** [comment]
Looks like it was a problem all about the update form. I haven't deleted the duplicates in the search server yet, but next time you upload/update a piece, please let me know if the number of duplicates on the search increases. I think it shouldn't anymore.

**Comment by slhowes** [comment]
Yes! The number of duplicates stays the same! Sometimes their titles change, but they aren't 'multiplying' anymore.
