### ISSUE TITLE
Some URL matches are over-inclusive

### ISSUE THREAD

**Issue by wabain** [ELVIS-Project/elvis-database#128]
Some of the URL rules are set up so that they match partial strings. For instance, this means that URLs like http://database.elvisproject.ca/about/foo/bar/ or http://database.elvisproject.ca/about/cats/ are sent the same response as http://database.elvisproject.ca/about/. The URL rules should probably test that the match extends from the start of the pathname to the end (e.g. `^about/$`).

**Comment by lexpar** [comment]
Good catch :+1:

**Comment by lexpar** [comment]
Fixed in 64175c5e9d1f8a3b7f4272e888527f0575f2b757
