### ISSUE TITLE
Update won't let me change link in comments

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#129]
Uploaded a new piece and copied the URL directly in:
![screen shot 2015-10-06 at 3 21 26 pm](https://cloud.githubusercontent.com/assets/13374693/10319806/26521018-6c3e-11e5-9869-8258413a5c04.png)

Went back to update it to include an actual link:

![screen shot 2015-10-06 at 3 21 48 pm](https://cloud.githubusercontent.com/assets/13374693/10319812/30e0f774-6c3e-11e5-8a2e-c1be8d89f5ef.png)

But when I click submit, it doesn't actually change anything, and the entry remains as it was before:

![screen shot 2015-10-06 at 3 21 26 pm](https://cloud.githubusercontent.com/assets/13374693/10319826/3ffd327c-6c3e-11e5-8773-2764a312666d.png)

Any idea what's going on?

**Comment by lexpar** [comment]
#124 references the same issuse. I'll close that one though, because this one has pictures. I haven't investigated this yet. I'll have a look sometime this week.

**Comment by emilyhopkins** [comment]
Ha! sorry I missed Sam's issue before posting.

**Comment by slhowes** [comment]
I'll take screenshots next time!

**Comment by lexpar** [comment]
Merry Christmas :p
