### ISSUE TITLE
Giving descriptions to collections 

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#131]
Looks like this used to be possible but is no longer? For example Jacob and Chris both have descriptions of their collections but mine (KernScores) just says  "No comment" -- and there is no field (that I have noticed) where I could comment.

![screen shot 2015-10-07 at 2 36 49 pm](https://cloud.githubusercontent.com/assets/13374693/10347243/02457e12-6d01-11e5-859d-dd441e0a1f91.png)

Was losing that feature deliberate? I don't know how important this is as a feature but maybe either:

1. add back the ability to add a description to collections
2. Print nothing instead of "No comment" so it doesn't look like anything is missing...

**Comment by AFFogarty** [comment]
Implemented in new GUI.
