### ISSUE TITLE
Home Page search function -- trouble with suggestions

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#133]
I was trying to see if the database had Byrd's "Ave Verum corpus", so I searched "byrd ave"

On the home page, it overrides my entry and searches for its suggestion, "Byrd, William", even if I don't accept the suggestion (and have typed "byrd ave") 

I think it's because I hit Enter to search and it accepts the auto-fill and then searches, instead of using my typed entry. If I mouse over and click the magnifying glass it's ok.

![screen shot 2015-10-08 at 2 45 31 pm](https://cloud.githubusercontent.com/assets/13374693/10376436/e565b958-6dcb-11e5-9251-4349d737afdd.png)

The search function in the database doesn't do the auto-suggesting and so it doesn't have this problem.

**Comment by lexpar** [comment]
Yup - the auto suggest pastes in its suggestion when you hit enter. It happens to be conflicting the the search form doing a search when you hit enter. 

Either you can only select suggestions by mouse, or you can only search by mouse. To me it seems natural to use the arrow keys to select a suggestion then hit enter, but maybe I should force the user to actually click the search button in this case so this doesn't happen all at once.

**Comment by emilyhopkins** [comment]
You could have it so the autosuggestions appear automatically, but with none highlighted, so that you need to arrow down in order to start highlighting one. 

(This appears to be how it works in google search box)

**Comment by lexpar** [comment]
good idea!
