### ISSUE TITLE
Search Page -- unexpected results

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#134]
When searching "byrd ave" in the database (not from the Search bar on the home page), it seems like it returns everything for Byrd or Ave, as opposed to connecting the two:

![screen shot 2015-10-08 at 2 44 01 pm](https://cloud.githubusercontent.com/assets/13374693/10376456/f5ab00ac-6dcb-11e5-94fd-7e960c3ed67c.png)

as you can see, I get Byrd-the-composer, and then Aves by anybody and everybody else. It would be helpful if it was more immediately obvious that there's nothing for byrd AND ave, (which I can get by using that boolean, "byrd AND ave") -- I'm not sure that the default makes the most sense.

**Comment by lexpar** [comment]
I fixed this at some point - go ahead and give this another shot! :)

**Comment by emilyhopkins** [comment]
hooray! looks like this is fine now. Makes it a lot easier for users to figure out if a specific piece has already been uploaded.
