### ISSUE TITLE
Add files endpoint to search.

### ISSUE THREAD

**Issue by lexpar** [ELVIS-Project/elvis-database#135]
Reiner pointed out it would be useful if there was an endpoint to get a big json list of **all** the files associated with a search, which would be great for writing scripts to index entire queries of files at once.

In the short term, he'd like the ability to get one large json list with all the files and their locations which correspond to a specific query - he's hoping to demonstrate this before the end of October, so the best thing to do might be to add a new endpoint that accomplishes exactly this.

In the long term, a lot more flexibility in the type of query parameters that can be sent in would be much better. Pagination, result types (objects or files), etc.

{filename: url,
filename: url}

**Comment by musicus** [comment]
:+1:

**Comment by lexpar** [comment]
Okay - all pieces and movements which have attached files now have an ``attached_files`` list in their search results. That should do it.

**Comment by musicus** [comment]
Great! It _just_ works.
