### ISSUE TITLE
"Last updated" for Collections 

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#138]
![screen shot 2015-10-13 at 4 31 34 pm](https://cloud.githubusercontent.com/assets/13374693/10467497/15a52860-71c8-11e5-965f-17016edabcf0.png)

The date updated should either reflect the most recent piece added or just not be displayed -- as-is it is redundant because there is already a separate line for date the collection was created.

**Comment by AFFogarty** [comment]
No longer appears on new GUI.
