### ISSUE TITLE
General search doesn't auto-suggest; could result in duplicates for composers with multiple spellings

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#139]
In the general search within the site, the search bar doesn't do auto-suggestion, which makes it hard to know if a given composer is in the database if there are multiple common versions of the name. 

For example: when searching Dunstable, Dunstaple doesn't pop up -- they are the same composer, but we prefer Dunstaple for the database. If I didn't know to look for another name, I'd add Dunstable as a separate composer. Auto-suggest in this part might help with that?

Ideally maybe we could add "aliases" or redirects or something, where on adding a composer for the first time you can also add other common spellings of the name/variants, but I get that the autocomplete should take care of a lot of this.

The other problem is composers like Du Fay, which is also commonly Dufay, because the suggestion won't kick in until it's too late... even if autosuggest were working in that part of the site, it wouldn't recognize "Duf" as a possible start for its "Du "

**Comment by lexpar** [comment]
Okay - search bar does auto-suggestion now.

Aliases are a good idea, especially for composers.

**Comment by lexpar** [comment]
It should be less broken and and suggesting now.

I still want to implement the 'nothing selected first' and <enter> searches what is entered, but you can scroll down the suggestions and <enter> pastes in the suggestion and search.
