### ISSUE TITLE
Improve downloads template/UI

### ISSUE THREAD

**Issue by lmok** [ELVIS-Project/elvis-database#14]
Implement (in order of priority):
Celery periodic/cron to remove day-old user_downloads files each day (done f22e481db88e533eee46e7a3870d63f6d27cc13b)
Handle bad requests nicely
Make prettier

**Comment by lexpar** [comment]
I just got an email from someone trying to download something from the download cart. His experience mirrors mine, which is that it throws 500 errors every time.

As far as I can tell the download cart doesn't work ever, so I'm going to make this a higher priority.

**Comment by lmok** [comment]
I just checked production -- Rabbit is down again. @ahankinson I remember there being a problem with sysctl not starting Rabbit properly on reboot (this is probably what happened) and you figured out a fix sometime last year. Do you remember what that was?

**Comment by lexpar** [comment]
Can you clarify a little? The problem is just that Rabbit isn't starting up on server reboot?

**Comment by lmok** [comment]
Wow ok, the summer heat must be getting to my head. I just noticed that the systemd unit was disabled and just needed re-enabling. It should work fine now. 

The problem I was referring to was due to a tweak made to SELinux a while ago that broke systemd + Rabbit, but it got fixed. No idea how the unit magically disabled itself sometime since, though.
