### ISSUE TITLE
General search bar "Enter" doesn't work to execute search

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#140]
If I type Schumann, Schubert, Beethoven, Ave, maria [stuff in the database] and then hit Enter, the word disappears and no search happens

If I type elephant, duck, crawford [not in the database] and then hit Enter the word just stays there...

If I click the magnifying glass the search proceeds normally, although no auto-suggest.

(I'm guessing this is just fall-out from trying to solve #139 ?)

**Comment by lexpar** [comment]
Should be less awful now.

**Comment by emilyhopkins** [comment]
I still have to click on the magnifying glass to do a search. 

But it is doing autosuggest and not deleting things when I hit enter! Progress!
