### ISSUE TITLE
Updating entries where "None" was entered for Number of Voices

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#141]
I noticed the genre "Symphon" popping up and decided to hunt it down and correct it. I found it here http://database.elvisproject.ca/piece/2842/ Notice the Number of Voices was originally entered as "None"

When I click update, the number of Voices field shows as empty (not "None") and it freaks out and goes unresponsive and eventually shows this message:

![screen shot 2015-10-15 at 5 43 24 pm](https://cloud.githubusercontent.com/assets/13374693/10528550/df45919e-7364-11e5-94d5-4c248c2f7103.png)

I'm guessing the Number of Voices field used to be less restrictive and the Update feature is not pleased about anything in there that's not a number?

**Comment by lexpar** [comment]
Thats bad!

**Comment by lexpar** [comment]
What browser is this in? It's not giving me problems on chrome or firefox.

**Comment by emilyhopkins** [comment]
News! I tried to update this piece again.

It let me change "Symphon" to "Symphony" and then it got stuck...

It kept freezing, occasionally the cursor would show up in the Number of Voices field or the Comment field (I was trying to select the Number of Voices field)

Then eventually it let me enter the number, and submit the changes! Something is definitely better, as it just got totally stuck and showed that error message every time the other day.

**Comment by lexpar** [comment]
Well I don't really know if anything is better. For some reason the script is entering into some infinite loop/recursion on firefox that it is not entering on Chrome. And it wasn't doing this before, either. I have to spend more time looking at it!

**Comment by AFFogarty** [comment]
Any progress on this?

**Comment by lexpar** [comment]
As far as I can tell, this particular instance is no longer causing issues, and I have not heard of it being reproducible anywhere else.
