### ISSUE TITLE
Red highlighting on categories I missed

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#146]
This is a minor problem... but hopefully easy to fix?

When I try to submit and I forgot a button, it highlights it in red.

When I click on the button, however, it stays red.
![screen shot 2015-10-23 at 12 44 50 pm](https://cloud.githubusercontent.com/assets/13374693/10700920/fef8280a-798e-11e5-801f-693a9f53db7f.png)

It might be nice if the red went away, to indicate that I had fulfilled the form's requirements successfully.

**Comment by lexpar** [comment]
I believe I fixed this at some point. Please let me know if this still effects you!

**Comment by AFFogarty** [comment]
Going to close this.
