### ISSUE TITLE
Not able to log in to ELVIS database

### ISSUE THREAD

**Issue by sagransj** [ELVIS-Project/elvis-database#147]
I have been having trouble logging into the ELVIS database on my Mac. I just tried to do so on Chrome, Firefox, and Safari, but nothing happened. I reset my password and it is still not working. Any idea what's going on? I click "sign in" but it just causes the sign in page to reload.

**Comment by lexpar** [comment]
I made the URL matching stricter and it broke a couple instances where I had input a 'sloppy' url which was accepted within the looser rule set. If you reload the login page it should be fixed.

**Comment by sagransj** [comment]
Okay, It is working now. Thanks!
