### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#149]
When choosing _[Collections](http://database.elvisproject.ca/collections/)_, collections by all the users are exposed. Perhaps the user should have the right to decide whether or not collections should be public or not.

**Comment by lexpar** [comment]
The owner of a collection can decide to make it private - in which case it won't show up in the search or the Collections browse page. Unless you mean something else, this feature already exists.

**Comment by musicus** [comment]
I made my collection private, and it still showed up public, thus I raised this issue.

**Comment by lexpar** [comment]
It should show up if you're logged into the account who owns it (which I assume you still are), or if you're a superuser. If you log out, or into a different account, it should be invisible and accessible.

**Comment by lexpar** [comment]
I think this is working as intended.
