### ISSUE TITLE
Downloading Files

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#150]
The _downloading files_ functionality is stuck at zipping. In effect no files can be downloaded from the interface (of course there are no problems downloading the files directly from a link in the JSON). This is an urgent issue since several people at SMT already have opened accounts in order to download and upload files.

**Comment by lexpar** [comment]
Celery was not happy with some directory permission changes. Got it working on me end. Let me know.

**Comment by lexpar** [comment]
Apologies that this wasn't working when you needed it to... Unfortunately it's still very much an in-development project, and the sole developer has scant time to devote to it.

**Comment by musicus** [comment]
Of course I understand :). Ha! It works...it's really more important that it works this evening while I show it off. Awesome!!! :+1:  :100:

**Comment by lexpar** [comment]
Okay -  glad to hear it.
