### ISSUE TITLE
Main Search Field Autocomplete

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#154]
When typing in a query for _Ockegehem_ in the simple, or advanced search field, autocomplete always adds information when hitting the _enter_ (or _return_) button(s), rather than just searching for _Ockeghem_. This does not happen when pushing the actual search button, thus the issues also becomes an accessibility issue).

**Comment by lexpar** [comment]
Yeah - I thought I made this better but it's worse. Should be *even better* now.
