### ISSUE TITLE
Search Drilldown

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#155]
When searching for _Josquin Des Prez_ and drilling down the information by selecting _Number of Voices_ (4), and then selecting the _motet_ tag, additional tags are selectable (like _uncertain attribution_, etc.), but the search results return _Nothing Found!_, even though there should be 25 results. In other words: selecting more than one tag results in _Nothing Found!_.

**Comment by lexpar** [comment]
Thanks for logging this - known about this issue for a while (don't think it ever worked).

**Comment by musicus** [comment]
Sweet!
