### ISSUE TITLE
Character encoding issue.

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#156]
When trying to retrieve Ockeghem's _Mort, tu as navré_ (http://database.elvisproject.ca/media/attachments/19/64/000000000001964/Mort,-tu-as-navr%C3%A9_Ockeghem,-Jean-de_file1.pdf) a 500 server error is thrown. When trying to retrieve the same file via a JSON query (the URL reads here: http://database.elvisproject.ca/media/attachments/19/62/000000000001962/Mort,-tu-as-navr/xc3/xa9_Ockeghem,-Jean-de_file1.pdf) a 404 server error is thrown.

**Comment by lexpar** [comment]
Yeah this looks shitty. Obviously an encoding issue with that 500 error.

**Comment by lexpar** [comment]
http://database.elvisproject.ca/piece/2491/

The attachments should all be there now... All files in the database have had unicode removed from their file names - note, we still have unicode in the titles of the pieces and such.

**Comment by lexpar** [comment]
Unless you've experienced any other problems with this, the normalization I did in November worked and this can be closed.

**Comment by musicus** [comment]
Great! (I have not, but will keep an eye on it as per use case.)
