### ISSUE TITLE
Downloading Files Page

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#159]
Provide a _Return to Search_ button, below the _Download Files_ button, stay on the page for 10-20 seconds provide a message that files have downloaded, and that user will be forwarded to the _Search_ page.

**Comment by lexpar** [comment]
On the page where your files get zipped together, with the progress bar?

**Comment by musicus** [comment]
Yes.

**Comment by lexpar** [comment]
Not relevant on dev.

**Comment by musicus** [comment]
ok.
