### ISSUE TITLE
404 Errors on first two Bach pieces

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#161]
When I search "Bach" the first two pieces I click on return 404 Errors

http://database.elvisproject.ca/movement/3526/
http://database.elvisproject.ca/piece/2884/

The rest on that page seem fine; I'm not sure what's wrong.

**Comment by lexpar** [comment]
These are the result of some duplicates in the search server right now. They're not actual objects (anymore), but the search server thinks they are. I think I'll re-index things on Thursday...

**Comment by lexpar** [comment]
This was fixed in November.
