### ISSUE TITLE
Collaborative Collections

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#167]
We are working on a project in which we have multiple contributors to a collection. As it is right now a person can create a collection for themselves, but no items can be transferred from one collection to another, or no pieces from the cart can be transferred to a specific collection, only new collections can be created. A button from the cart that says "Add to Collection" (next to "Save as Collection") that then brings up a modal window from which the Collection can be chosen, either as a list, or a dropdown autocomplete, or a combination of both, would work. 

This is a relatively high priority issue since Sam, Ian, Nina, Marina, Julie, and I (the _we_) are assembling a dataset  (_Dodecachordon Data Set_, which I created in December).

**Comment by musicus** [comment]
(not really a bug, just higher priority)

**Comment by lexpar** [comment]
> Ideally, only a set of assigned users should be able to add, edit, or delete items to a dataset, or collection. 
> -musicius

I'm going to merge all these issues here. #168 and #165 are duplicates of this same feature request - unless I'm missing something?

**Comment by musicus** [comment]
No. Perfect. Thank you! :+1:

**Comment by AFFogarty** [comment]
Has any progress been made on this?

**Comment by musicus** [comment]
None that I can see. This issue was first raised December 13th.

**Comment by AFFogarty** [comment]
Setting to "IN PROGRESS" because I have made progress on #189.

**Comment by AFFogarty** [comment]
I've broken the "Add to Collection" button feature out into a new issue so that we can be more precise with tracking.

Thus, I will mark this issue as duplicate because it is really two issues: #189 and #194 .

**Comment by musicus** [comment]
Ok, sounds good!
