### ISSUE TITLE
Strip illegal characters from file names

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#170]
Uploaded files should have spaces, commas, periods, etc. removed from the file names.

**Comment by lexpar** [comment]
Here's where files are renamed will being uploaded (they only exist here temporarily).
https://github.com/ELVIS-Project/elvis-database/blob/master/elvis/views/views.py#L136

Here's the function an Attachment object uses to take the temporary file, rename it, and place it in the correct directory for the object.
https://github.com/ELVIS-Project/elvis-database/blob/master/elvis/models/attachment.py#L67

Already stripping spaces on upload, `/` is stripped and unicode normalized on file_attach.

**Comment by AFFogarty** [comment]
@musicus says that we should also strip commas.

**Comment by musicus** [comment]
(strip and subtitute "," > "-")

**Comment by lexpar** [comment]
Are periods an issue? I don't think periods are an issue. Maybe I should replace periods with '_'.

**Comment by musicus** [comment]
I have not found an issue. However, most of the time periods indicate some type of file or directory attribute (file extensions, etc.). "-" here would be great as well, since the underscore divides the title of a piece from a composer.

**Comment by lexpar** [comment]
I don't think I should remove periods. They don't cause naming issues, and are an easy edge case to fuck up with a parser that replaces them, given the need for maintaining and checking against the extensions of files.

**Comment by musicus** [comment]
Language. I think you should, except of course when they are part of the file extension. It just makes a file look much cleaner, e.g.: _Ave-Maria-virgo-serena_Josquin-Des-Prez_file1.mei_ looks better than _Ave-Maria...-virgo-serena_Josquin-Des-Prez_file1.mei_.

**Comment by musicus** [comment]
@lexpar & @AFFogarty - OK, I just double checked [here (Stanford Libraries)] (https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming), and periods are fine. So we can have all alphanumeric characters, "-","_", and "." and noting else.

**Comment by lexpar** [comment]
Perfect. 

My issue was that removing periods didn't get us anything besides aesthetics, but that it would be fairly easy to forget or miss some edge case while writing the sanitizing function and accidentally chop off the extension.

**Comment by fujinaga** [comment]
Please try not to swear. You are in a public space.

Ich

**Comment by lexpar** [comment]
No problem. Cleaned it up.

**Comment by AFFogarty** [comment]
I've modified the RegEx a bit so that we don't get multiple dashes.

**Comment by musicus** [comment]
Grrrrrrreat!

**Comment by AFFogarty** [comment]
So now the file for my piece `Andrew's Piece/kl1@(!$$--1-41244$$$;ll,,.12j4u1824--++_!,test------------a` will be called `Andrew-s-Piece-kl1-1-41244-ll-.12j4u1824-_-test-a_Fogarty-Andrew_file1.mei`.

**Comment by AFFogarty** [comment]
Added some code to handle edge cases where the piece name or composer name are empty after sanitization.

In these cases, we use a hash function to generate placeholder names.

**Comment by lexpar** [comment]
So - when the piece or name of the composer is nothing but punctuation and spaces?

**Comment by musicus** [comment]
Exactly...like a bot composer.

**Comment by AFFogarty** [comment]
:+1:

**Comment by AFFogarty** [comment]
Ok, I'm going to go ahead and close this.

**Comment by musicus** [comment]
:100:
