### ISSUE TITLE
Renaming compositions should update file names

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#171]
If a superuser renames a composition, it should also rename the corresponding files.

**Comment by AFFogarty** [comment]
I have not been able to reproduce this bug.  @musicus, could you provide more in-depth reproduction instructions?

**Comment by AFFogarty** [comment]
This seems to reproduce on master but not on dev, so I will close it for now.

**Comment by lexpar** [comment]
It's because I fixed it in df802e845f3b8f2356b541d56f348991f115f173

**Comment by musicus** [comment]
:+1:

**Comment by AFFogarty** [comment]
Oops my mistake.

**Comment by lexpar** [comment]
This is what we were talking about for the last week with the file renaming functions @AFFogarty  haha.
