### ISSUE TITLE
Cannot zip multiple files with same name

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#172]
If multiple files with the same name are zipped, only the last of them is actually included.

This might be caused by file name enumerations not working properly.

**Comment by lexpar** [comment]
Not a bug on dev branch.

**Comment by lexpar** [comment]
Actually, this is still broken if a composer happens to have 2 PIECES with the exact same names (movements are fine). Since this is technically possible, I'll reopen.

**Comment by AFFogarty** [comment]
Has this been fixed?  I have not been able to reproduce it.  I have two pieces with the same composer and piece name, and when I download the zip it contains these files:

```
Andrew-s-Piece-1234_Fogarty-Andrew_file1-0.mei
Andrew-s-Piece-1234_Fogarty-Andrew_file1.mei
Andrew-s-Piece-1234_Fogarty-Andrew_file2.mei
```

**Comment by lexpar** [comment]
Yes It has been fixed. `CartZipper._de_dupe_name(target_dir, name)` will check if a file named `name` already exists in `target_dir`. If so, it will split name into a `(prefix,ext)` tuple and try inserting a '-i' between the two up to 1000 times in an attempt find a free name for the file. Your example is a perfect picture of intended behaviour.

**Comment by AFFogarty** [comment]
kewl
