### ISSUE TITLE
Additional file formats for upload to the ELVIS data

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#175]
We should also allow the following additional symbolic music file formats for upload to the database:

- NoteArray (symbolic music encoded for Mathematica), or _.ma_
- MuseData (which we allow already as _.md_, but not the newer), or _.md2_
- JSON Piano Roll, or _.json_

**Comment by lexpar** [comment]
Fixed on dev branch.

**Comment by musicus** [comment]
:+1:
