### ISSUE TITLE
Login Encryption

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#177]
We need encryption for the log in procedure.

**Comment by wabain** [comment]
Cantus Ultimus needs this too, once we acquire SSL certs (DDMAL/cantus#166). Since [Let's Encrypt](https://letsencrypt.org/) is in public beta now, that might be the way to go.

**Comment by lexpar** [comment]
I emailed @ahankinson a short while ago about this, and he recommended getting a cert from Let's Encrypt as well.

**Comment by AFFogarty** [comment]
Seeing as how we're using token authentication, wouldn't this mean moving the entire site to HTTPS?

**Comment by lexpar** [comment]
It would probably be worthwhile. The main reason I (and R, I assume) are worried about the log in page in particular is that its not very nice of use to send people's passwords as plain text in a POST.

If every other page was unencrypted, the tokens would not be truly valuable at preventing hijacking someone's privileges or session data, but that stuff is less harmful (still harmful, still possible in principle for someone to easily hijack a super-users auth-token and delete the contents of the DB). That seems a lot less pressing and likely than our unencrypted transmission of passwords.

**Comment by lexpar** [comment]
This has been done for weeks (?) months (?)  year (?)-- long time.
