### ISSUE TITLE
dev availability

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#186]
The dev site should not be accessible off campus (unless VPN is used).

**Comment by AFFogarty** [comment]
Emailed McGill IT about how to proceed with this.  Awaiting response...

Also, should we be discussing this issue on this public forum?

**Comment by ahankinson** [comment]
Uhm... can't you just restrict it on the machine firewall? 132.206.0.0/16, 132.216.0.0/16

**Comment by AFFogarty** [comment]
Ok, I have NGINX blocking connections outside those IPs.  Do those IPs represent music tech or all of McGill?

**Comment by ahankinson** [comment]
Most of McGill.

**Comment by AFFogarty** [comment]
Hmm... my devices on wi-fi seem to be blocked.

**Comment by ahankinson** [comment]
Yes. *most* of McGill, except Wifi.

**Comment by AFFogarty** [comment]
We have temporarily disabled the IP blocking so that @lexpar can work on his laptop.  We will re-enable the firewall once McGill IT gets back to me with the proper IP rules that allow for wi-fi and VPN access.

**Comment by ahankinson** [comment]
http://whois.arin.net/rest/org/MCGILL-Z/nets

132.206, 132.216, and 142.157 should cover the VPN, wired, and wireless cases.

**Comment by AFFogarty** [comment]
Alright, it's working now.  Going to close this issue.

**Comment by musicus** [comment]
:+1:
