### ISSUE TITLE
Collection Curators

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#189]
Moderators are users who can add pieces to a collection they do not own.

Moderators are not owners, and therefore cannot delete the collection.

Part of #167.

**Comment by lexpar** [comment]
So are they moderators of a single collection? Or all the collections?

**Comment by AFFogarty** [comment]
It's a `ManyToMany` relationship.

**Comment by lexpar** [comment]
So when modifying a collection, the owner of the collection can assign moderation privileges to other users. Is that is?

**Comment by AFFogarty** [comment]
"Moderators" will be renamed to "Curators".

**Comment by AFFogarty** [comment]
Closing this because curators are pretty much implemented on the back-end.
