### ISSUE TITLE
1-Click Dev Deployments

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#191]
I'm writing a script to automate `dev` deployments.  This technique will make it much easier to deploy builds.

The script clones the dev branch, sets up the virtual environment with requirements.  The current build is moved to a back-up location.

Later on, we will adapt this script for 1-Click `prod` deployments.

**Comment by ahankinson** [comment]
Is this compatible with the Rodan build process? We should make sure we don't have too many different build systems in place.

See: https://github.com/DDMAL/Rodan-deployment

**Comment by AFFogarty** [comment]
As far as I can tell, the Rodan tool's scope is much larger than the scope of this tool.

**Comment by lexpar** [comment]
I don't think you're doing this in Vagrant are you @AFFogarty? The current deployments are not virtualized in any way.

**Comment by ahankinson** [comment]
How so? They're both running celery, django, database, etc. Rodan has a few more moving parts, but the basics are pretty much the same.

**Comment by AFFogarty** [comment]
@lexpar Nope.  This tool merely clones the repo, configures the Python virtual environment, and performs Django maintenance tasks (collecting static files, migrating database, etc.).

**Comment by lexpar** [comment]
I think @AFFogarty's goal here was to write a shell script that can quickly get the dev server running on a different box in the near future (Compute Canada).

I fooled around with Docker pretty extensively a few weeks ago, but we haven't done anything official towards putting the project in a virtual machine or in docker containers. Do you think it's still worth doing? My experience with docker was that it actually complicated the structure of the project pretty hugely, and it's supposedly not suitable for deployments, so I ended up leaving that branch alone.

**Comment by AFFogarty** [comment]
Ok, the script now successfully backs up the old build, clones the repo, and configures the app.

The only thing is that after running the script, we have to manually add my username to `gunicorn_start_dev.sh`.

**Comment by lexpar** [comment]
Fixed in 040f01d59675f0404d375d92f3ff3743e4d7df8b
