### ISSUE TITLE
File Download

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#203]
The file download didn't immediately work. Only when I refreshed the page and tried anew did it work. The celery logs did report that the files was properly downloaded the first track. This error seems to be JavaScript related, and may be hard to replicate ... I used Chrome Version 48.0.2564.116 (64-bit), and OS X 10.10.5.

**Comment by lexpar** [comment]
It could very well be that there was some elements of the page that were still cached, and thus out of date and incompatible with the new version. Let us know if it happens again!

**Comment by musicus** [comment]
Definitely a JavaScript issue. Consistently happens on my system, then I refresh, and I'm good to go...

**Comment by AFFogarty** [comment]
Yeah I think that this is a front-end JS issue.  We're not seeing any errors in our Celery logs.

**Comment by AFFogarty** [comment]
Ok, I now think that this might be a Celery configuration issue on the server.  It looks like `prod` Celery requests are actually being routed to the `dev` Celery.  Investigating...

**Comment by musicus** [comment]
Ha!

**Comment by AFFogarty** [comment]
Ok, the problem is definitely from having concurrent `prod` and `dev` Celery runners.

**Comment by AFFogarty** [comment]
I have disabled the `dev` Celery worker so that the `prod` worker will take precedence.  It seems to be working.

**Comment by musicus** [comment]
:neckbeard:

**Comment by AFFogarty** [comment]
Seeing as how we have isolated and fixed this "bug" from a usability perspective (file downloads do indeed work in production), I think that we should mark this Issue as fixed.

We can then create a new GitHub issue corresponding to enhancing our Celery workers so that we can have a `dev` and a `prod` worker running simultaneously.
