### ISSUE TITLE
Downloaded Directory

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#205]
The directory structure looks good for the most part, but should be structured like the following:
```
Zip-File
  Composer
    Title
      meta
      Movement
```

**Comment by lexpar** [comment]
I'm not sure if I undertand this issue, and I *really* don't understand it if 9263d709cea4af85d9ac24a0a9b5e6d01c1ef9f6 fixed it!

**Comment by musicus** [comment]
If it's fixed its fixed :+1:
