### ISSUE TITLE
Dynamic "Corpus" creation

### ISSUE THREAD

**Issue by ahankinson** [ELVIS-Project/elvis-database#21]
A corpus is a custom collection of pieces/movements. Right now, corpora are static entities.

A corpus should be changed to essentially be a saved download cart.

1. User adds pieces to their cart
2. User goes to their cart
3. They either have the option to download the files, or to save them in a corpus

To figure out:

1. Should all corpora be visible to all users? (I say yes).
2. Can a user delete/modify a corpus once it's been created? (Also, yes, but maybe not?)

To this end we should think about renaming the "Download" area at the top, possibly to "View Corpus"? In section they would either have the option to save as a corpus, or to download all the files.

The advantage of this is that a user can create a corpus and then pull this corpus into the VIS web app without downloading and then uploading files, or searching in the web app.

**Comment by lexpar** [comment]
I added this!
