### ISSUE TITLE
Dev and Prod Celery Workers

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/elvis-database#210]
Right now, only one `Elvis` Celery worker can be running on the server at a time.

If we try to have a `dev` worker and a `prod` worker, then the workers end up stepping on each other's toes and the download functionality of the application stops working.

We need to figure out a way to have a `dev` worker and a `prod` worker running simultaneously without errors.

**Comment by AFFogarty** [comment]
Ok @lexpar, I tested your fix in `dev` and it seems to be working.  So, I say that for now we mark this as `FIXED`.  We will re-open this issue if there are problems when we deploy `v3.0.2`.

**Comment by fujinaga** [comment]
Can you run them on different servers?

**Comment by AFFogarty** [comment]
@fujinaga They would definitely work if `dev` and `prod` were on separate servers.

**Comment by lexpar** [comment]
I think we solved the problem though, so it shouldn't be necessary.
