### ISSUE TITLE
Redundant Collection entries

### ISSUE THREAD

**Issue by lexpar** [ELVIS-Project/elvis-database#216]
http://database.elvisproject.ca/collection/2/

This collection (and many others) has a ton of redundant entries... Almost every movement that is listed is part of one of the pieces in the collection. I'm not sure exactly how this happened. It may be a bug in the piece-creation logic - or it could have occurred during some data migration event. In any case, we should write a script to trim 'redundant' movement entries from existing collections and run it on the DB, and try to discern where this undesired action happens.

**Comment by AFFogarty** [comment]
So, if a piece is in a collection, then the piece's movements shouldn't also be in the collection independently?

**Comment by lexpar** [comment]
Exactly. While a piece is in your download cart it prevents you from adding or removing the movements of that piece... Since they are already 'there' because the piece is there.

If you add one of these redundant collections to your cart... Well, it might not add both the pieces and their movements since the ElvisCart controls for that sort of thing, but it would try to! 

It's an inconsistent representation and erroneous for sure.

**Comment by AFFogarty** [comment]
Ok, here's a hypothetical situation, where M is a movement and P is a piece containing M:

1. Add M to collection.
2. Add P to same collection.
3. Remove P from the collection.

Should M still be in the collection after this?

**Comment by lexpar** [comment]
No, it shouldn't and it doesn't.

The way it's conceptualized is adding/removing a 'parent' to the cart applies the same action to all its children.

**Comment by AFFogarty** [comment]
Ok, so, I think that the solution to this is to give the `Collection` model `add_piece()`, `remove_piece()`, `add_movement()`, and `remove_movement()` methods.

These methods would contain logic that would prevent the invalid `Collection` states described in this issue.

We could also create an admin command called `fix_invalid_collections` that scans all collections and corrects any invalid states.

**Comment by lexpar** [comment]
The ElvisCart has the methods you described. Since a cart and a collection are supposed to follow the same logic, you should be able to co-opt them almost verbatim. 

We should also write a script to re-align existing collections with this expectation.

**Comment by lexpar** [comment]
Should be simple:
```python

for c in Collection.objects.all():
    for m in c.movements.all():
        if m.piece in c.pieces.all():
            c.movements.remove(m)
```

**Comment by AFFogarty** [comment]
:+1:

**Comment by AFFogarty** [comment]
Ok, so now we can write code like

```
if piece in collection:
    # do something
```

**Comment by AFFogarty** [comment]
Ok, I've tested this on Dev and it seems to be working.  So let's close the issue.  If the problem comes up again, then we can re-open this issue.
