### ISSUE TITLE
Add pieces from cart to existing collection

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#217]
One should be able to add pieces in a cart to an existing collection (I'm sure this is a duplicate issue ... I've seen the ```add to existing collection``` button already on DEV?). One can create an empty collection but not add pieces to that collection.

**Comment by lexpar** [comment]
This is already up and working on the collection-editing branch!

**Comment by AFFogarty** [comment]
Actually, the collection editing branch has already been merged into `dev`.

**Comment by musicus** [comment]
I thought so. :+1:
