### ISSUE TITLE
Remove copyrighted/restricted/other files that cause problems to bring the db back to the public

### ISSUE THREAD

**Issue by vee-L** [ELVIS-Project/elvis-database#222]
There should be a way to deal with the possibility of those later on too.

**Comment by lexpar** [comment]
Have we gotten complaints about rights? I only heard vaguely last Saturday that downloads had been shut off. Was there a particular incident/complaint, or are we just being defensive?

I think because files are uploaded by users we are not directly responsible for copy-right issues if we make reasonable attempts to delete copyright content from our service once we receive a complaint. Of course I don't know any specifics about this stuff, but how could any user-content driven service operate if they could be held directly responsible for the files their users uploaded?

**Comment by vee-L** [comment]
Honestly I agree with you, I think we should delete the ones who are there already though, if needed.

**Comment by fujinaga** [comment]
Yes, we had a complaint from Stanford's CCARH.

**Comment by vee-L** [comment]
So, after this discussion, is there still a need for a "secret access" kind of collection or should we just remove the files that caused the complaint? I feel like most websites just take these down, and the legalities of it still aren't clear to me. Unless there is a way to make sure the user creating the collection has the rights to the material (which I don't know about).

**Comment by vee-L** [comment]
I'll give the admin the possibility to hide pieces/movements for now.

**Comment by lexpar** [comment]
That's a good idea @vee-L! Note: you will probably want to duplicate the 'hidden' flag in solr so that hidden pieces don't show up in search results.

**Comment by ahankinson** [comment]
Or not index them in solr in the first place...

**Comment by musicus** [comment]
I'm with @ahankinson on the solr issue.

**Comment by lexpar** [comment]
That works too. I was thinking of how we implemented public/private collections. In that case, it made sense to index things and put a private flag on them, so we could still show those results to the user who owned the collection. I thought it might make sense for admins to still be able to search for hidden pieces.

**Comment by ahankinson** [comment]
Nah, I think just being able to find/change them in the Django admin interface is enough.

**Comment by lexpar** [comment]
Good point!

**Comment by musicus** [comment]
The files need to be removed.

**Comment by lexpar** [comment]
Have we got a list of offending files? I could disable downloads on them today if so (well, I could do it soon anyway).

**Comment by ahankinson** [comment]
Downloads are already disabled for non-McGill people while we sort this out.

**Comment by lexpar** [comment]
Right, but Ich says there was a complaint, and Reiner just said we need to remove the files. I'm asking if we have a list of which files exactly need to be removed to comply with the complaint and move forward.

**Comment by musicus** [comment]
We need to compile the list, regardless of what we do with the materials, so we can bring the fully functional ELVIS database back online as soon as possible.

**Comment by ahankinson** [comment]
Ian has come up with a list of the files that are infringing. However, rather than simply deleting these files and moving on, I think it's best if we wait until @vee-L finishes the Piece/Movement hiding functionality.

That way we can hide the pieces and movements with infringing encodings, delete the CCARH files, and then (potentially) attach non-infringing encodings.

**Comment by lexpar** [comment]
Ok! Sounds like a plan. Sorry if I'm demanding a lot of attention with these questions: I've fallen out of touch with what's going on with this project, but still very much want to see it do well.

**Comment by vee-L** [comment]
I've branched this from master instead of dev for now since I'm assuming the deployed website is running from master, is that ok?

**Comment by lexpar** [comment]
Makes sense 2 me. Dev is pretty far ahead of master right now, but we can definitely reconcile everything in the future after you fix this critical stuff!

**Comment by ahankinson** [comment]
The pattern is that the production site is deployed from master, the development site is deployed from dev.

**Comment by musicus** [comment]
Great! Shouldn't it be a new release though? Right now it is listed as [3.0.2](https://github.com/ELVIS-Project/elvis-database/releases) in the footer. @vee-L could you update the release notes?

**Comment by lexpar** [comment]
Yeah for sure. 3.0.3? It's kind of a feature, but mostly its a patch.

**Comment by musicus** [comment]
major.minor.patch :-)

**Comment by imlorenz** [comment]
I think there is still an issue with the pieces that we are hiding on the database.  I have hidden all of the Beethoven string quartets that appear on the ELVIS database, but some of the files are still accessible even if they are hidden.  For example, all of the "Movements not in a Piece" can be accessed, and I haven't been able to find them on the admin portion of the database.  Although, perhaps we could simply delete these "other files" as they seem to be duplicates of files contained in pieces.

Also, I think it might be problematic that people can see the files that exist on the database in spite of their being hidden.  For instance, when typing in Beethoven on the database, all of the string quartets appear, but they just can't be accessed.  I think it might be better to completely hide them from view of the public without deleting them, if such a thing is possible.

**Comment by musicus** [comment]
Added bug label as to @imlorenz comments ... perhaps it should be a new issue?

**Comment by vee-L** [comment]
Also I found another specific quirk when searching in advanced search, I'll look into the things mentioned too. The hiding from suggestions is something I wanted to do, it just proved to be very difficult, but I can give it another go.

**Comment by vee-L** [comment]
@imlorenz  do you mean that there are movements that don't seem to be in the database (from the admin interface point of view) that can be accessed on the website? That seems very strange even without considering the hiding issue.... or did you mean that you hid these piece-less movements yet they are still accessible?

**Comment by imlorenz** [comment]
@vee-L The pieces that I am talking about specifically are the files listed under "movements not in a piece."  I wasn't able to find them from the admin interface but they were still accessible to view and download.  In any event, I think we should just delete these files because they seem to be duplicates of the pieces that we are hiding.

**Comment by vee-L** [comment]
I think I've fixed why you weren't able to find them, they will be find-able and hide-able once this is deployed.

**Comment by vee-L** [comment]
Will be deployed Monday morning.

**Comment by lexpar** [comment]
Things have been hidden, and will soon need to be unhidden.
