### ISSUE TITLE
Downloads Sometimes Have the Same Name

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/elvis-database#38]
Currently, the "zip" files downloaded from the EDDA are given a filename according to the downloader's username and the date of download. This means people downloading more than one query on the same day will have conflicting filenames.

I suggest either lengthening the time stamp, adding a sequence number, or adding a pseudo-random number to the filename.

**Comment by lexpar** [comment]
Fixed in 2cbf8acb750339ceff04c408a5f3aa97b317697e
