### ISSUE TITLE
Import Tables from Old Site

### ISSUE THREAD

**Issue by lmok** [ELVIS-Project/elvis-database#40]
Need to import files and metadata from the old site. The tags in the old system have been re-structured as being instances of genre, instrumentation, language, location, and source models. There's a csv with the appropriate tag reassignments floating around somewhere -- have to ask Julie for the latest version. The plan was to read the csv in and look up new genres/instrumentations etc with respect to the old tags, before inserting the old data into the new database.

See #4 .

**Comment by lexpar** [comment]
Closed as I duplicated this issue in #54
