### ISSUE TITLE
Facet checkboxes are not aligned.

### ISSUE THREAD

**Issue by ahankinson** [ELVIS-Project/elvis-database#58]
On my browser the checkboxes in the faceted search are not aligned with their labels. This needs to be fixed.

**Comment by lexpar** [comment]
Could you post a screenshot and tell me which browser you're on? They look fine on Chrome and Firefox to me.

**Comment by ahankinson** [comment]
I'm on Safari


![facets](https://cloud.githubusercontent.com/assets/163183/8877988/6bba7486-3220-11e5-8746-6839a41430b9.png)

**Comment by lexpar** [comment]
Would you check again to see if c855d1cf003006b7cabd5d90ddfe11ba4a432c1e fixed it? Looks aligned on my Mac.

**Comment by ahankinson** [comment]
Looks good.
