### ISSUE TITLE
"Collections" is confusing

### ISSUE THREAD

**Issue by ahankinson** [ELVIS-Project/elvis-database#62]
Why is it called "collections?" Can't it just be "Downloads"?

**Comment by lexpar** [comment]
Do you mean in the top right on the nav?

**Comment by ahankinson** [comment]
Yes.

**Comment by ahankinson** [comment]
Looks good, but the buttons on pieces still say "add to collection", when (I think) they should say "Add to downloads" or something like that.

see: http://database.elvisproject.ca/piece/1983/

**Comment by ahankinson** [comment]
Perhaps "Add to Downloads" instead of "Add to Cart"?

**Comment by lexpar** [comment]
Fixed in ef7db107f380bca4a95dbde0f6677def9fb5f70b
