### ISSUE TITLE
Fix title for Upload a Piece page

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#75]
On the Upload a Piece page the title that appears in the browser tab is "Create a Piece" -- it should all say "Upload"

**Comment by lexpar** [comment]
Well the "upload" link leads to the create a piece page... I don't really know if I should change this.

**Comment by emilyhopkins** [comment]
I see what you mean. I remember there being an inconsistency between the page and the browser tab before that isn't showing up now, so at least it's consistent.

In terms of the actual word choice "Create" -- to me "Create a Piece" sounds more like composing, and I think "Upload a Piece" or "Enter a Piece" is more appropriate in all instances. Do you want me to consult Nina and Jacob to see what they think? This could just be me nitpicking!

**Comment by lexpar** [comment]
I see what you mean... I think I'll change it to Upload a Piece
