### ISSUE TITLE
Clicking "Download" on the cart page may take a long time to do anything if cart is large.

### ISSUE THREAD

**Issue by lexpar** [ELVIS-Project/elvis-database#78]
I'm doing a lot of processing on the ajax request before sending back an OK - this is why it seems unresponsive on large carts.

The button function should be changed so it loads the page right away, and the files can be loaded in by ajax afterwards.

**Comment by ahankinson** [comment]
I think Celery should handle all of the zipping and processing in a separate thread, so there's really no reason to do any processing in view handler.

**Comment by lexpar** [comment]
The deal is that the Download model tracks Pieces, Movements, and Files. When you click download, it looks at all the Pieces and Movements and copies their attachments over to Files before giving you a big list. I wasn't thinking about carts with 500+ things in them when I wrote this.

The solution is to just have the files added to Files at the same time as the pieces and movements are added to the downloads.

**Comment by lexpar** [comment]
And, yeah, once you select the files, the 'downloading' page loads instantly because celery is doing the zipping.

**Comment by lexpar** [comment]
Fixed in d181e51f5b9810a669597c78cb59bbb5d7b5cc94
