### ISSUE TITLE
Composition Start/End Date Fields

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#80]
After entering a date (where I can type it in) I can only increment up or down one year at a time -- this is awkward if there was a typo or if a bigger change needs to be made. Can we have incrementing OR re-entry as options?

**Comment by lexpar** [comment]
Now you can delete stuff that you wrote in to the field. Fixed in c068818ab2ac1b27a93f1c303a5d88167cc09c0d

**Comment by emilyhopkins** [comment]
This one still doesn't work for me.

**Comment by lexpar** [comment]
Yup, still broken on firefox I see.

**Comment by lexpar** [comment]
Fixed in 9fe16723a6305d5e839080605b6b2c479e186432
