### ISSUE TITLE
Go to Piece and Leave/Stay on Page Warning

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#82]
When finished uploading a piece, I am given the option to "Go to Piece" and then when I click it I get a warning about staying/leaving the page so I don't lose data I've entered. Clicking "Go to Piece" should override the "Do you want to stay on this page? etc..." warning because it's all just been saved anyways.

**Comment by lexpar** [comment]
This was working in chrome, I swear!

Fixed in eb284ff083486d2a510e99ac2d93e338f83f239f
