### ISSUE TITLE
Lists of movements in collections/ naming movements

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#83]
The movements need to have the information about which piece they're from more visible. Perhaps add another column that adds the piece data to the movement file listing as well? (This is to avoid a long list of Allegro, Allegro, Andante, Allegro, etc)

**Comment by lexpar** [comment]
Fixed in 45ac66af6604203b2d18ff8a4a529654de7eddb2

Added parent-piece info, date info, composer info, and all in sortable tables.
