### ISSUE TITLE
Movement files should require File Source as well

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#85]
Currently only the Piece Files table requests a File Source; since we're not supposed to upload in both tables there should be a File Source required in the Movement Files table as well.

**Comment by lexpar** [comment]
Emily - please check out the new way files and movements are input in the upload form, and tell me if it makes more sense.

Fixed in 3a8630b0cb8d9aad2d217b903bd5bc04303a13c4

**Comment by emilyhopkins** [comment]
I like it a lot. Thanks for working on this! Just a few things:

1) I might change the Files table text:

_Upload files here in XXXXX formats. If the file is for a specific act or movement as entered above, select that entry from the drop-down menu._

[if they didn't enter movements/acts there won't be a dropdown so this might be specific enough?]

2) And also the movements text:

_If the work is divided into movements, acts, or other parts, declare them in this table. Many inputs from the previous page may be overridden on a per-movement basis by clicking the 'show advanced' button._

3) Is it possible to hit "Enter" or "OK" or something similar when creating a movement? It's not super intuitive that clicking away automatically saves it. (minor point, obviously it does work as-is)

4) Do you think it would be better to put the comments box below the movements? This might help associate the Movements with the piece information and keep the data entry part more conceptually separate from the file-uploading part.

**Comment by lexpar** [comment]
1 and 2: no problem.

3: The movement isnt actually saved in the database until the form is submitted... As it is, the movement form is like any of the other inputs on the upload page, you can just duplicate it as many times as you want. When you put stuff in the inputs, its just as 'saved' as every other input on the screen. Adding an 'OK' button would not really be particularly easy or helpful I think.

4. I think it's equally useful to have the movements close to the files, where you can see the difference adding/removing something from one table produces on the other. Also, you can override comments on movements, so if you had the movement table first, you'd be prompted to override something you haven't even declared yet (this won't cause a bug, its just conceptually confusing).

**Comment by emilyhopkins** [comment]
OK, I think the way it is makes sense then. Thanks for clarifying. (For the movements entry I think I was expecting to have to do more to get it to show up in the drop-down below, but obviously I don't).

**Comment by lexpar** [comment]
Yeah! I managed to rig it in such a way that the dropdowns are updated as soon as a 'movement title' input *loses* focus. So, whenever a title is (ostensibly) entered, but without need additional confirmation or element refreshing :)

**Comment by emilyhopkins** [comment]
That's actually pretty cool :)

Will you be updating the text too? Not trying to nag, just didn't want it to get lost since the issue's been closed.

**Comment by emilyhopkins** [comment]
Also! The Movements text should actually read:

_If the work is divided into movements, acts, or other parts, declare them in this table. Many inputs from *above* may be overridden on a per-movement basis by clicking the 'show advanced' button._

(It still says previous page even though the upload is one page now)

**Comment by emilyhopkins** [comment]
Similarly the Additional Fields text needs to be revised since it's all on one page now. Since we're explaining each individual box so thoroughly anyways, perhaps it could be shorter?:

"These fields make it easier to find the piece using the database search engine. Multiple inputs should be separated by semicolons. If this piece has movements (defined below) you can override these fields for individual movements. "

Or something like that.
