### ISSUE TITLE
Composition Start and End dates: Year reads "NONE-1793"

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#86]
For pieces with only one year for composition, the entry sheet says to only put a date in the second box (Composition End Date). When I do this, the entry prints "NONE-1793" (for example). It should just read "1793."

**Comment by lexpar** [comment]
On what page/pages does it do this?

**Comment by emilyhopkins** [comment]
Sorry, it's in the information for the piece when I go to my collections and look at the string quartets I've uploaded. It's in some of Jacob's pieces too; older and more recent uploads. 

(I would include a link but it's not letting me login right now?! Not sure if that's somehow me or if something else is up... I'm using the same username/password as last week)

**Comment by lexpar** [comment]
Sign in is working for me... That's really odd.

**Comment by lexpar** [comment]
You're going to have to give me a screenshot, because I'm not seeing this NONE anywhere.

**Comment by emilyhopkins** [comment]
Tried with both my email as username (which has previously worked) and the username I have on there (emilyhopkins)
It's entirely possible it's all me, I just don't know what I'm doing differently! I promise my capslock isn't on :P

<img width="1920" alt="screen shot 2015-08-10 at 12 20 29 pm" src="https://cloud.githubusercontent.com/assets/13374693/9176604/4342f63a-3f5a-11e5-8e38-6ab8738b02c0.png">
<img width="1920" alt="screen shot 2015-08-10 at 12 20 45 pm" src="https://cloud.githubusercontent.com/assets/13374693/9176605/4344f368-3f5a-11e5-9f72-184ef2cc709b.png">

**Comment by emilyhopkins** [comment]
Login problem solved sorry. Screenshot of None:

<img width="1920" alt="screen shot 2015-08-10 at 12 25 50 pm" src="https://cloud.githubusercontent.com/assets/13374693/9176721/ff21b922-3f5a-11e5-82c2-3e17dc0ab6ce.png">

**Comment by lexpar** [comment]
Fixed in fbd109ea7b6167fd1d531474e1977bf156f0b76b

**Comment by lexpar** [comment]
http://database.elvisproject.ca/collection/53/

Still an issue.

**Comment by lexpar** [comment]
Fixed in 0c736feb357db506f069f35032bc0c8105ede070
