### ISSUE TITLE
request correction to instructions under Movements

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#91]
Since the form is only one page, the following instruction was confusing to me: "Many inputs from the previous page may be overridden on a per-movement basis by clicking the 'Show Advanced' button." I think this should read "To modify the inputs above on a per-movement basis, click on the 'Show Advanced' button."

**Comment by emilyhopkins** [comment]
I mentioned this in issue #85 (either way it needs updating, along with anything else that still implies it's multiple pages for the upload screen)

**Comment by lexpar** [comment]
Fixed in a2ee94563c99db2a41bd884f7efc5e4d18289727
