### ISSUE TITLE
change to Composer tooltips

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#93]
The second bullet should read: "If you add a new composer, input the name "First, Last" and employ the spelling conventions of Grove Music Online." When I entered the first Wagner piece, I mistakenly only included his last name when most other entries include the given name(s) as well. And when this database is used outside of the academy, some users may not know what "Grove" is.

**Comment by lexpar** [comment]
I can add this and change the name of 'Wagner' tomorrow.

**Comment by NinaPenner** [comment]
Thanks. Just to be clear:
Wagner should be changed to "Wagner, Richard"
And also Gluck should be changed to "Gluck, Christoph Willibald"

Thanks,

Nina
