### ISSUE TITLE
Reference an existing piece when adding new movements

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#94]
I'm not sure what exactly your plan is for implementing user editing, but this is an important part of it that came up when Nina and when I was first trying to upload things as well.

Say a piece has already been entered, either by you or someone else. If you want to upload more movements or files, ideally, you could reference that piece's information (composer, dates, etc) both to avoid tediousness and so that there aren't inconsistencies introduced, resulting in multiple, slightly different entries of the same piece.

I know this is tricky because being able to have multiple pieces with the same title is important, just something to bear in mind.

**Comment by lexpar** [comment]
I could make a version of the update form where you can only add movements and files... This could be available to not-(uploader of piece) and not-(superuser). Uploaders and superusers will be able to edit everything....

**Comment by emilyhopkins** [comment]
That sounds like a good solution to me.

@NinaPenner does that make sense to you?

**Comment by NinaPenner** [comment]
Sounds good to me too.

**Comment by lexpar** [comment]
Super user's can add movements and files to pieces without redundant field entries. I've moved the meat of this issue into #169.

**Comment by ahankinson** [comment]
:meat_on_bone: 

Also, "Superusers," no apostrophe.

**Comment by lexpar** [comment]
meat_on_bone has absolutely no meaning to me haha.

**Comment by lexpar** [comment]
OH **meat** of this issue.
