### ISSUE TITLE
Update form doesn't recognize religiosity or vocalization

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#95]
When I try to submit updates (I deleted my erroneous "piece" files that were actually movements) it prompted me to enter religiosity and vocalization, even though those were inevitably part of the original piece -- it doesn't seem to be able to fill those from the older entry. (I'm guessing it's just because they're a different kind of entry field)

**Comment by emilyhopkins** [comment]
Also FYI I tried just clicking the right button for Secular and Instrumental and then submitting and it won't save my file changes.

<img width="1920" alt="screen shot 2015-08-13 at 4 48 23 pm" src="https://cloud.githubusercontent.com/assets/13374693/9261341/33b162fa-41db-11e5-890c-0ff481839069.png">

**Comment by lexpar** [comment]
Firefox and Chrome where returning different values on a few of my calls. Fixed in 7f7ebdca00c7d30956fc4f460fa780f7bc796d76
