### ISSUE TITLE
edit to "Modify Existing Piece" instructions

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#96]
In the instructions that pop up immediately when you click "Update", the bullet point "Do not modfiy any fields that you do not wish to change." seems redundant to me. I would remove it. If it is to be retained, there's also a typo in the word "modify".

**Comment by lexpar** [comment]
Well -  I don't think it's completely redundant. I agree that it's possibly obvious, but I can also see some people finding the pre-filled form a little confusing. I will fix the typo though.

**Comment by lexpar** [comment]
Fixed in 9675a8c021fd0edf84af32fe60bc6e794f0c2e27
