### ISSUE TITLE
edit to "Additional Information" instructions

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/elvis-database#99]
Please revise "(e.g., Tags: D-Sharp; Motet)" to  "(e.g., Tags: D-Sharp Minor; 4/4)". First, it's not clear what "D-Sharp" is referring to with out "Minor" or "Major" after it. And your advice that "Motet" might be a good tag to include goes against the advice about not repeating information in other fields ("Motet" should be entered under "Genre").

**Comment by lexpar** [comment]
Great suggestion!

Fixed in 9675a8c021fd0edf84af32fe60bc6e794f0c2e27
